### ISSUE TITLE
文字乱码问题

### ISSUE THREAD

**Issue by xulihang** [xulihang/ImageTrans-docs#398]
有用户在Windows中文环境下遇到乱码问题，原因不是很明确。不过可以通过外部css指定字体来解决这个问题。

![image](https://user-images.githubusercontent.com/5462205/235439752-a6756596-e856-4076-867e-00a5deaa933e.png)

新建一个目录，取名比如叫`css`，在里面放一个`font.css`文件，内容如下：

```css
.root {
    -fx-font-family: SimHei;
}
```

在偏好设置里启用外部css：

![image](https://user-images.githubusercontent.com/5462205/235440025-9a35a283-7ed5-4906-ae6e-9007391cb1d4.png)
