### ISSUE TITLE
可以让气泡框在排版模式时勾选一直隐藏不显示吗？

### ISSUE THREAD

**Issue by yahoozhu** [xulihang/ImageTrans-docs#636]
主要气泡框调整位置时容易造成视错觉，明明居中了也看不出来，要点过去移动时才能进行隐藏，经常要移动后才发现已经居中了
希望能勾选一直隐藏，这样在翻译校对完，字体大小角度调整完，最后进行居中对准的时候我也不需要出现气泡框了，只要点选字体中央直接拖动就行，或者让气泡框颜色可编辑也行，最后切换个背景色也好

**Comment by xulihang** [comment]
我加个设置吧，可以自己用CSS去定义边框样式，比如用下面的样式让边框变成一个个点的样式。

```css
#textBox {
  -fx-border-style:dotted
}
```

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/ed5716a5-2988-4231-8897-929548d6a6ab)

**Comment by xulihang** [comment]
宽度颜色这些在代码里写死了，CSS没有效

**Comment by xulihang** [comment]
要强制使用的话得这样用，加个`!important`：

```css
#textBox {
  -fx-border-style: dashed;
  -fx-border-color: blue !important;
  -fx-border-width: 10 !important;
}
```

**Comment by xulihang** [comment]
下个版本再完善下，选中和不选中的样式可以这样设：

```css
#textBox {
  -fx-border-style: dashed;
}

#textBox:focused {
  -fx-border-style: dashed;
  -fx-border-color: blue !important;
}
```

**Comment by xulihang** [comment]
v2.12.0对CSS做了完善。选中、拖动状态下的样式也能设了

```css
#textBox {
  -fx-border-style: dashed;
}

#textBox:focused {
  -fx-border-style: dashed;
  -fx-border-color: blue !important;
}

#textBox:hold {
  -fx-border-width: 0 !important;
}
```
